# Generated by Django 4.1 on 2023-02-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=50, verbose_name='title')),
                ('link', models.URLField(default='no link', verbose_name='link')),
                ('link_company', models.URLField(default='no link', verbose_name='link_company')),
                ('name_company', models.CharField(default='no name_company', max_length=50, verbose_name='name_company')),
                ('salary', models.CharField(default='not provided', max_length=30, verbose_name='salary')),
                ('description', models.CharField(default='no description', max_length=250, verbose_name='description')),
                ('location', models.CharField(default='-', max_length=250, verbose_name='location')),
            ],
            options={
                'verbose_name': 'Vacancy in England',
                'verbose_name_plural': 'Vacancies in England',
                'ordering': ['-salary'],
            },
        ),
        migrations.CreateModel(
            name='Vacancies_northireland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=50, verbose_name='title')),
                ('link', models.URLField(default='no link', verbose_name='link')),
                ('link_company', models.URLField(default='no link', verbose_name='link_company')),
                ('name_company', models.CharField(default='no name_company', max_length=50, verbose_name='name_company')),
                ('salary', models.CharField(default='not provided', max_length=30, verbose_name='salary')),
                ('description', models.CharField(default='no description', max_length=250, verbose_name='description')),
                ('location', models.CharField(default='-', max_length=250, verbose_name='location')),
            ],
            options={
                'verbose_name': 'Vacancy in Northern Ireland',
                'verbose_name_plural': 'Vacancies in Northern Ireland',
                'ordering': ['-salary'],
            },
        ),
        migrations.CreateModel(
            name='Vacancies_scotland',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=50, verbose_name='title')),
                ('link', models.URLField(default='no link', verbose_name='link')),
                ('link_company', models.URLField(default='no link', verbose_name='link_company')),
                ('name_company', models.CharField(default='no name_company', max_length=50, verbose_name='name_company')),
                ('salary', models.CharField(default='not provided', max_length=30, verbose_name='salary')),
                ('description', models.CharField(default='no description', max_length=250, verbose_name='description')),
                ('location', models.CharField(default='-', max_length=250, verbose_name='location')),
            ],
            options={
                'verbose_name': 'Vacancy in Scotland',
                'verbose_name_plural': 'Vacancies in Scotland',
                'ordering': ['-salary'],
            },
        ),
        migrations.CreateModel(
            name='Vacancies_wales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no title', max_length=50, verbose_name='title')),
                ('link', models.URLField(default='no link', verbose_name='link')),
                ('link_company', models.URLField(default='no link', verbose_name='link_company')),
                ('name_company', models.CharField(default='no name_company', max_length=50, verbose_name='name_company')),
                ('salary', models.CharField(default='not provided', max_length=30, verbose_name='salary')),
                ('description', models.CharField(default='no description', max_length=250, verbose_name='description')),
                ('location', models.CharField(default='-', max_length=250, verbose_name='location')),
            ],
            options={
                'verbose_name': 'Vacancy in Wales',
                'verbose_name_plural': 'Vacancies in Wales',
                'ordering': ['-salary'],
            },
        ),
    ]
