"""Initial migration.

Revision ID: 80ab735f2861
Revises: 
Create Date: 2022-12-29 12:15:35.964776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ab735f2861'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cafe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('map_url', sa.String(length=500), nullable=False),
    sa.Column('img_url', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=250), nullable=False),
    sa.Column('seats', sa.String(length=250), nullable=False),
    sa.Column('has_toilet', sa.Boolean(), nullable=False),
    sa.Column('has_wifi', sa.Boolean(), nullable=False),
    sa.Column('has_sockets', sa.Boolean(), nullable=False),
    sa.Column('can_take_calls', sa.Boolean(), nullable=False),
    sa.Column('coffee_price', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cafe')
    # ### end Alembic commands ###
