# Generated by Django 4.1 on 2022-08-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='no name', max_length=50, verbose_name='Name')),
                ('anons', models.CharField(default='no anons', max_length=250, verbose_name='Anons')),
                ('full_text', models.TextField(verbose_name='Arrticle')),
                ('date', models.DateTimeField(verbose_name='Date of publication')),
            ],
        ),
    ]
