# Generated by Django 4.1 on 2022-09-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_account_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profileimg.jpg', null=True, upload_to=''),
        ),
    ]
