# Generated by Django 4.1 on 2022-09-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0008_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profileimg.jpg', null=True, upload_to='images'),
        ),
    ]
